name: flutter_rainbow_border
description: "This package allows you to create a rotating rainbow border."
version: 1.0.0
homepage: https://github.com/rwr9857/flutter-rainbow-border

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: